### ISSUE TITLE
Error on init

### ISSUE THREAD

**Issue by JamesBrandts** [remix-pwa/remix-pwa#121]
When I use npx remix-pwa@latest init it show the following message, after I choose the options:
No `remix.config.js` file found in your project. Please make sure to run in a remix project or create one and try again or 
alternatively, run `remix-pwa --help` for more info.

The project is a remix app, it has a remix.config.js, that's on the root directory and I choose the app directory (default).

I just cant figure a way to implement push notifications properly on my remix app.

The project: https://github.com/JamesBrandts/easyschedule

**Comment by ShafSpecs** [comment]
Hello 👋, thanks for reaching out. This is very weird bug indeed, can you please re-try and post a screenshot of the console (if possible?)

**Comment by JamesBrandts** [comment]
Just tried install it on a codespace and it installed correctly, I must have something weird in my local system. Perhaps some incompatible version on a dependency. Hope when I merge it to main everything work fine.
Thank you

**Comment by JamesBrandts** [comment]
> > Just tried install it on a codespace and it installed correctly, I must have something weird in my local system.
> 
> Please what Operating System do you use locally?

Locally I'm using Windows 10

**Comment by ShafSpecs** [comment]
> > > Just tried install it on a codespace and it installed correctly, I must have something weird in my local system.
> > 
> > 
> > Please what Operating System do you use locally?
> 
> Locally I'm using Windows 10

Try again locally but this time, run `npx remix-pwa@dev init`

**Comment by ShafSpecs** [comment]
Try `init` again :+1:

**Comment by JamesBrandts** [comment]
Tried it again on my project in windows, tried creating a new remix project from scratch, on windows 10 and on codespace I get the error:
$ npx remix-pwa@latest init
Need to install the following packages:
remix-pwa@3.0.8
Ok to proceed? (y) y
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@remix-run/dev' imported from /home/codespace/.npm/_npx/2a790d8a53532af9/node_modules/@remix-pwa/dev/dist/compiler/compiler.js
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:780:9)
    at moduleResolve (node:internal/modules/esm/resolve:829:20)
    at defaultResolve (node:internal/modules/esm/resolve:1034:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:375:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:344:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:220:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v20.6.1
![Error REMIX-PWA](https://github.com/remix-pwa/remix-pwa/assets/91541345/52a83fe4-3887-40cf-9527-5bfdb2493890)

**Comment by ShafSpecs** [comment]
Did you install deps.? before running the command 😕 

I can't reproduce this error and it seems like it isn't just you getting it

**Comment by ShafSpecs** [comment]
Oh wait, I forgot to add something - run `npx remix-pwa@dev init`. `dev` tag is for nightly builds, I haven't pushed it to stable yet

**Comment by JamesBrandts** [comment]
For the `npx remix-pwa@dev init`, in all environments, I get the following error:

npm ERR! code ETARGET
npm ERR! notarget No matching version found for remix-pwa@dev.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in: /home/codespace/.npm/_logs/2023-09-22T20_51_07_390Z-debug-0.log


![Error REMIX-PWA 2](https://github.com/remix-pwa/remix-pwa/assets/91541345/2e6c6546-c059-4601-a8f5-27bcab490ca8)
[2023-09-22T20_51_07_390Z-debug-0.log](https://github.com/remix-pwa/remix-pwa/files/12704556/2023-09-22T20_51_07_390Z-debug-0.log)

**Comment by ShafSpecs** [comment]
This is a Windows-only issue so far, would debug well this weekend

**Comment by JamesBrandts** [comment]
> Did you install deps.? before running the command 😕
> 
> I can't reproduce this error and it seems like it isn't just you getting it

The `emptyModulesPlugin ` is exported in the end of @remix-run/dev/dist/compiler/plugins/emptyModules.js

This is my '@remix-run/dev/dist/compiler/plugins/emptyModules.js'


```
/**
 * @remix-run/dev v2.0.1
 *
 * Copyright (c) Remix Software Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE.md file in the root directory of this source tree.
 *
 * @license MIT
 */
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var path = require('node:path');

function _interopNamespace(e) {
  if (e && e.__esModule) return e;
  var n = Object.create(null);
  if (e) {
    Object.keys(e).forEach(function (k) {
      if (k !== 'default') {
        var d = Object.getOwnPropertyDescriptor(e, k);
        Object.defineProperty(n, k, d.get ? d : {
          enumerable: true,
          get: function () { return e[k]; }
        });
      }
    });
  }
  n["default"] = e;
  return Object.freeze(n);
}

var path__namespace = /*#__PURE__*/_interopNamespace(path);

/**
 * This plugin substitutes an empty module for any modules in the `app`
 * directory that match the given `filter`.
 */
function emptyModulesPlugin({
  config
}, filter, {
  includeNodeModules = false
} = {}) {
  return {
    name: "empty-modules",
    setup(build) {
      build.onResolve({
        filter
      }, args => {
        if (includeNodeModules ||
        // Limit this behavior to modules found in only the `app` directory.
        // This allows node_modules to use the `.server.js` and `.client.js`
        // naming conventions with different semantics.
        path__namespace.resolve(args.resolveDir, args.path).startsWith(config.appDirectory)) {
          return {
            path: args.path,
            namespace: "empty-module"
          };
        }
      });
      build.onLoad({
        filter: /.*/,
        namespace: "empty-module"
      }, () => {
        return {
          // Use an empty CommonJS module here instead of ESM to avoid "No
          // matching export" errors in esbuild for stuff that is imported
          // from this file.
          contents: "module.exports = {};",
          loader: "js"
        };
      });
    }
  };
}

exports.emptyModulesPlugin = emptyModulesPlugin;

```

**Comment by ShafSpecs** [comment]
<img width="861" alt="image" src="https://github.com/remix-pwa/remix-pwa/assets/69679506/bd8eca69-5c58-49cf-9b28-76ebcd542e0b">

@JamesBrandts booted up a VM to reproduce the error, not sure but according to this VM, the issue should be fixed in `remix-pwa@3.0.9`

**Comment by JamesBrandts** [comment]
Now it completes the installation perfectly on codespace, on windows I still get this error, but it's doesn't seem to be a big deal, as it seems to be a windows only problem, I can create those files manually or push them from a codespace. Thanks for the help.

![Error REMIX-PWA 3](https://github.com/remix-pwa/remix-pwa/assets/91541345/be9bcb60-1830-483d-82df-53a5001b7ffc)

**Comment by ShafSpecs** [comment]
No problem. Would still look at it this weekend though, what's the error text please? Github CDN is not loading any images

**Comment by JamesBrandts** [comment]
The error reads:

PS G:\Github\remix-pwa test> npx remix-pwa@3.0.9
This command is getting deprecated soon. Please use `npx remix-pwa@latest init` instead.
√ Is this a TypeScript or JavaScript project? Pick the opposite for chaos! · ts
√ Do you want to integrate workbox into your project? (y/N) · false
√ Do you want to utilise precaching in this project? (y/N) · false
√ What features of remix-pwa do you need? Don't be afraid to pick all! · sw, manifest
√ Where is your Remix `app` directory located? · app
√ What package manager do you use? · npm      
√ Do you want to run npm install? (Y/n) · true
⠋ Integrating Service Worker...
⠋ Integrating Web Manifest...
✔ Successfully ran npm install!
⠙ Integrating Web Manifest...
[Error: ENOENT: no such file or directory, open 'G:\G:\Github\remix-pwa%20test\app\routes\manifest[.]webmanifest.ts'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'G:\\G:\\Github\\remix-pwa%20test\\app\\routes\\manifest[.]webmanifest.ts'
}
[Error: ENOENT: no such file or directory, open 'G:\G:\Github\remix-pwa%20test\app\entry.worker.ts'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'G:\\G:\\Github\\remix-pwa%20test\\app\\entry.worker.ts'
⠋ Integrating Web Manifest...

⠼ Integrating Service Worker...

**Comment by wonu** [comment]
> The error reads:
> 
> PS G:\Github\remix-pwa test> npx remix-pwa@3.0.9 This command is getting deprecated soon. Please use `npx remix-pwa@latest init` instead. √ Is this a TypeScript or JavaScript project? Pick the opposite for chaos! · ts √ Do you want to integrate workbox into your project? (y/N) · false √ Do you want to utilise precaching in this project? (y/N) · false √ What features of remix-pwa do you need? Don't be afraid to pick all! · sw, manifest √ Where is your Remix `app` directory located? · app √ What package manager do you use? · npm √ Do you want to run npm install? (Y/n) · true ⠋ Integrating Service Worker... ⠋ Integrating Web Manifest... ✔ Successfully ran npm install! ⠙ Integrating Web Manifest... [Error: ENOENT: no such file or directory, open 'G:\G:\Github\remix-pwa%20test\app\routes\manifest[.]webmanifest.ts'] { errno: -4058, code: 'ENOENT', syscall: 'open', path: 'G:\G:\Github\remix-pwa%20test\app\routes\manifest[.]webmanifest.ts' } [Error: ENOENT: no such file or directory, open 'G:\G:\Github\remix-pwa%20test\app\entry.worker.ts'] { errno: -4058, code: 'ENOENT', syscall: 'open', path: 'G:\G:\Github\remix-pwa%20test\app\entry.worker.ts' ⠋ Integrating Web Manifest...
> 
> ⠼ Integrating Service Worker...

This error occurs when there are no `/app` or `/app/routes` directories.
If the directories exist, and `entry.worker` or `manifest` doesn't exist, the default files are copied into those directories.

More appropriate error messages would be helpful.

**Comment by ShafSpecs** [comment]
> > The error reads:
> > PS G:\Github\remix-pwa test> npx remix-pwa@3.0.9 This command is getting deprecated soon. Please use `npx remix-pwa@latest init` instead. √ Is this a TypeScript or JavaScript project? Pick the opposite for chaos! · ts √ Do you want to integrate workbox into your project? (y/N) · false √ Do you want to utilise precaching in this project? (y/N) · false √ What features of remix-pwa do you need? Don't be afraid to pick all! · sw, manifest √ Where is your Remix `app` directory located? · app √ What package manager do you use? · npm √ Do you want to run npm install? (Y/n) · true ⠋ Integrating Service Worker... ⠋ Integrating Web Manifest... ✔ Successfully ran npm install! ⠙ Integrating Web Manifest... [Error: ENOENT: no such file or directory, open 'G:\G:\Github\remix-pwa%20test\app\routes\manifest[.]webmanifest.ts'] { errno: -4058, code: 'ENOENT', syscall: 'open', path: 'G:\G:\Github\remix-pwa%20test\app\routes\manifest[.]webmanifest.ts' } [Error: ENOENT: no such file or directory, open 'G:\G:\Github\remix-pwa%20test\app\entry.worker.ts'] { errno: -4058, code: 'ENOENT', syscall: 'open', path: 'G:\G:\Github\remix-pwa%20test\app\entry.worker.ts' ⠋ Integrating Web Manifest...
> > ⠼ Integrating Service Worker...
> 
> This error occurs when there are no `/app` or `/app/routes` directories. If the directories exist, and `entry.worker` or `manifest` doesn't exist, the default files are copied into those directories.
> 
> More appropriate error messages would be helpful.

I think i have spotted the cause for the error 👍, the CLI is trying to read the files before writing to them

**Comment by ShafSpecs** [comment]
Published a possible workaround?

**Comment by wonu** [comment]
The ENOENT error still occurs on WSL too.
Could you please delete the `app` or `app/routes` directory and try again?

I think the cause of the error is that the CLI is trying to write a file to a directory that doesn't exist.
So the 'slow down' workaround seems irrelevant, or please tell me what I'm missing.

My possible solutions are
1. throws error with proper message
2. creates all necessary directories silently

For most common Remix apps this error will not occur.
But what if an app uses custom `routes` and there is no `app/routes` directory? (weird though..)
I think both solutions 1 and 2 would be applicable in this case.

Or what if set custom `appDirectory` and made a typo in the CLI?
Then solution 2 wouldn't make sense.
Maybe it would be better to read `remix.config.js` and set it automatically.

**Comment by ShafSpecs** [comment]
> I think the cause of the error is that the CLI is trying to write a file to a directory that doesn't exist. So the 'slow down' workaround seems irrelevant, or please tell me what I'm missing.

I am not certain, but remix-pwa uses a `recursive` mode when reading & creating directories.

> My possible solutions are
>
> 1. throws error with proper message
> 2. creates all necessary directories silently

Number 1 is doable but complicated because node can throw exceptions from within normal functions and traceable error messages are not priority for me because a CLI is supposed to never crash imo, especially a simple one.

Regarding number 2, yes it would take some extra steps but I could explicitly define the directories before even reading to them.

> For most common Remix apps this error will not occur.
> But what if an app uses custom routes and there is no app/routes directory? (weird though..)
> I think both solutions 1 and 2 would be applicable in this case.

Very true indeed 😅.

 > Or what if set custom appDirectory and made a typo in the CLI?
> Then solution 2 wouldn't make sense.
> Maybe it would be better to read remix.config.js and set it automatically.

I tried to avoid reading `remix.config` file due to windows error but I think I have an explicit stack trace I can use: https://github.com/remix-pwa/remix-pwa/issues/123

**Comment by ShafSpecs** [comment]
One thing I forgot to note (not that it matters anymore, but if the entered a wrong appDirectory, there was a validation function that alongs the line of:
```ts
validate(input: string) {
            if (input === '') {
              return 'Please enter a valid directory';
            }

            pathExists(resolve(projectDir, input)).then(exists => {
              if (!exists) {
                return 'Please enter a valid directory';
              }
            });

            return true;
          },
          format(value) {
            return value.replace(/^\/|\/$/g, '');
          },
```

**Comment by ShafSpecs** [comment]
> The ENOENT error still occurs on WSL too. Could you please delete the `app` or `app/routes` directory and try again?

Do you mean deleting the file in the user project? This would work if it's a new project, but if I add it to an existing project in production, I break it entirely.

**Comment by wonu** [comment]
> Do you mean deleting the file in the user project? This would work if it's a new project, but if I add it to an existing project in production, I break it entirely.

Right, I just wanted to tell you how to reproduce the error :)

> I am not certain, but remix-pwa uses a recursive mode when reading & creating directories.

Here is where I think the problem is:

https://github.com/remix-pwa/monorepo/blob/cc5969be09c5611d6e3145e05a858f7f90330f63/packages/dev/cli/create.ts#L72

Same for `entry.worker`.
And when error occurs, `ora` spinner spins forever.

**Comment by ShafSpecs** [comment]
> > Do you mean deleting the file in the user project? This would work if it's a new project, but if I add it to an existing project in production, I break it entirely.
> 
> Right, I just wanted to tell you how to reproduce the error, and possible scenarios? :)
> 
> > I am not certain, but remix-pwa uses a recursive mode when reading & creating directories.
> 
> Here is where I think the problem is:
> 
> https://github.com/remix-pwa/monorepo/blob/cc5969be09c5611d6e3145e05a858f7f90330f63/packages/dev/cli/create.ts#L72
> 
> Same for `entry.worker`. And when error occurs, `ora` spinner spins forever.

Looks awfully familiar to past iterations of the CLI: https://github.com/remix-pwa/remix-pwa/blob/d08ca99c1d7af444a358a3531d46280474c774f4/cli.ts#L32

**Comment by wonu** [comment]
> Because it is meant to run on an already working Remix application.

I may sound stupid, but I didn't know until I saw the message `No remix.config.js file found in your project` because the installation docs is not clear about it.

So, I just copied and pasted `remix.config.js` out of curiosity, and then I got the ENOENT error.

As you said, ENOENT errors should not occur in a normal remix project, but I thought that there might be cases where the `app` or `app/routes` directories do not exist.

It's not a serious issue, so you can just ignore it. :sweat_smile:

**Comment by ShafSpecs** [comment]
Is this issue fixed? @JamesBrandts

**Comment by JamesBrandts** [comment]
I ended up making my own implementation of the features instead of using this package. I'll look into using this package in the future, seems very promising.

Thanks for your attention.

**Comment by antonioandrade** [comment]
@ShafSpecs here's a demo of the issue on two platforms (**Mac + Node 18** and **Debian + Node20**): https://d.pr/v/Ty5zhc

**Comment by ShafSpecs** [comment]
> OMG, just re-read the whole thread here:
> 
> > Because it is meant to run on an already working Remix application.
> 
> **NOT CLEAR AT ALL FROM THE DOCS : (** remix-pwa homepage is very misleading too... trying that now but it leaves me wondering what the compatibility is like in terms of remix versions too.

How misleading? I understand and agree the docs didn't explicitly state a working Remix app was needed (my bad), but that's how it works. Should update the docs later this week. Vite + Remix PWA has been consuming my time more recently

**Comment by antonioandrade** [comment]
@ShafSpecs appreciate all your effort on this project, this is all very promising!

I mean misleading here:
<img width="1458" alt="image" src="https://github.com/remix-pwa/remix-pwa/assets/1588621/85a426f0-33cd-42fe-b486-d03c61cb146f">

It's not single step to start a new project, it's two steps: `npx init remix` (or whatever), then `npx init remix-pwa`

I think it's also important to note somewhere on the docs (Installation) which remix versions are supported (1 and 2?) and in case, whether any remix v2 feature flags have an impact here (supported or not).

**Comment by ShafSpecs** [comment]
Noted 👍. Would make required changes later on, thanks for the heads up

**Comment by ShafSpecs** [comment]
*New Remix PWA site with new docs and more in the works so I would tick this off as completed +1*
